# Generated by Django 2.2 on 2021-06-05 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tranceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranceiver_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Switch100M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_model', models.CharField(max_length=100)),
                ('HBASET', models.CharField(max_length=20)),
                ('HFX', models.CharField(max_length=20)),
                ('HEX', models.CharField(max_length=20)),
                ('HZX', models.CharField(max_length=20)),
                ('HBD', models.CharField(max_length=20)),
                ('HBU', models.CharField(max_length=20)),
                ('transceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hp.Tranceiver')),
            ],
            options={
                'ordering': ['switch_model'],
            },
        ),
    ]
