# Generated by Django 2.2 on 2021-06-05 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Switch100M',
            new_name='Switch_100M',
        ),
    ]
