# Generated by Django 2.2 on 2021-06-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0003_auto_20210605_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch_100m',
            name='HLX',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='switch_100m',
            name='HFX',
            field=models.CharField(max_length=20),
        ),
    ]
