# Generated by Django 2.2 on 2021-06-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0004_auto_20210605_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch_1G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_model', models.CharField(max_length=100)),
                ('G_T', models.CharField(max_length=20)),
                ('G_SX', models.CharField(max_length=20)),
                ('G_LX', models.CharField(max_length=20)),
                ('G_LH', models.CharField(max_length=20)),
                ('G_EX', models.CharField(max_length=20)),
                ('G_ZX', models.CharField(max_length=20)),
                ('G_EZX_100KM', models.CharField(max_length=20)),
                ('G_EZX_120KM', models.CharField(max_length=20)),
                ('G_BD', models.CharField(max_length=20)),
                ('G_BU', models.CharField(max_length=20)),
                ('transceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hp.Tranceiver')),
            ],
            options={
                'ordering': ['switch_model'],
            },
        ),
    ]
