# Generated by Django 2.2 on 2021-06-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hp', '0005_switch_1g'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch_10G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_model', models.CharField(max_length=100)),
                ('SR', models.CharField(max_length=20)),
                ('LRM', models.CharField(max_length=20)),
                ('LR', models.CharField(max_length=20)),
                ('ER', models.CharField(max_length=20)),
                ('ZR', models.CharField(max_length=20)),
                ('XFP_SR', models.CharField(max_length=20)),
                ('XFP_LR', models.CharField(max_length=20)),
                ('XFP_ER', models.CharField(max_length=20)),
                ('XFP_ZR', models.CharField(max_length=20)),
                ('DAC_05M', models.CharField(max_length=20)),
                ('DAC_1M', models.CharField(max_length=20)),
                ('DAC_3M', models.CharField(max_length=20)),
                ('DAC_5M', models.CharField(max_length=20)),
                ('DAC_7M', models.CharField(max_length=20)),
                ('DAC_10M', models.CharField(max_length=20)),
                ('DAC_15M', models.CharField(max_length=20)),
                ('AOC_7M', models.CharField(max_length=20)),
                ('AOC_10M', models.CharField(max_length=20)),
                ('AOC_20M', models.CharField(max_length=20)),
                ('X2_SR', models.CharField(max_length=20)),
                ('X2_LRM', models.CharField(max_length=20)),
                ('X2_LR', models.CharField(max_length=20)),
                ('X2_ER', models.CharField(max_length=20)),
                ('X2_ZR', models.CharField(max_length=20)),
                ('transceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hp.Tranceiver')),
            ],
            options={
                'ordering': ['switch_model'],
            },
        ),
    ]
